# Generated by Django 4.2.5 on 2023-11-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0004_remove_post_created_at_remove_post_deleted_at_and_more'),
        ('posts_api', '0005_like_created_at_post_comment_count_and_more'),
    ]

    operations = [
    ]
