# Generated by Django 4.2.5 on 2023-11-07 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0007_post_created_at_post_deleted_at_post_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts_api.post'),
        ),
    ]
