# Generated by Django 4.2.5 on 2023-11-07 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0008_remove_post_deleted_at_remove_post_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='posts_api.post'),
        ),
    ]
