# Generated by Django 4.2.7 on 2023-11-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0011_postmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
