# Generated by Django 4.2.7 on 2023-11-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0012_alter_postmedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
