# Generated by Django 4.2.5 on 2023-10-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0002_initial'),
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='lectures',
            field=models.ManyToManyField(related_name='lectures', to='courses_api.academiclevelcourse'),
        ),
        migrations.AlterField(
            model_name='schoolelder',
            name='courses_attending',
            field=models.ManyToManyField(related_name='school_elders_courses', to='courses_api.academiclevelcourse'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses_attending',
            field=models.ManyToManyField(related_name='student_courses', to='courses_api.academiclevelcourse'),
        ),
    ]
