# Generated by Django 4.2.5 on 2023-10-19 21:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_api', '0003_alter_academiclevel_level'),
        ('users_api', '0003_alter_lecturer_biography_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='followers',
            field=models.ManyToManyField(related_name='lecturer_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='lectures',
            field=models.ManyToManyField(related_name='lectures', to='courses_api.academiclevelcourse'),
        ),
        migrations.AlterField(
            model_name='schoolelder',
            name='courses_attending',
            field=models.ManyToManyField(related_name='school_elders_courses', to='courses_api.academiclevelcourse'),
        ),
        migrations.AlterField(
            model_name='schoolelder',
            name='followers',
            field=models.ManyToManyField(related_name='school_elder_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses_attending',
            field=models.ManyToManyField(related_name='student_courses', to='courses_api.academiclevelcourse'),
        ),
    ]
