# Generated by Django 4.2.5 on 2023-09-28 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_user_is_authenticated_alter_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 6, 41, 38, 569890, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 6, 41, 38, 569936, tzinfo=datetime.timezone.utc)),
        ),
    ]
