# Generated by Django 4.2.5 on 2023-11-05 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 22, 16, 49, 674709, tzinfo=datetime.timezone.utc)),
        ),
    ]
