# Generated by Django 4.2.5 on 2023-10-01 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0007_chat_forum_messagecontent_schoolelder_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 1, 23, 51, 40, 134524, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 1, 23, 51, 40, 135584, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 1, 23, 51, 40, 134931, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='participantsforum',
            name='entry_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 1, 23, 51, 40, 136102, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 23, 51, 40, 128064, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('PreDoc', 'Pre Doctorate'), ('PhD', 'PhD'), ('Pr', 'Professor')], default='L1', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 23, 51, 40, 128095, tzinfo=datetime.timezone.utc)),
        ),
    ]
