# Generated by Django 4.2.5 on 2023-10-01 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0008_alter_chat_created_at_alter_forum_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 1, 23, 53, 3, 355933, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 1, 23, 53, 3, 357036, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 1, 23, 53, 3, 356393, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='participantsforum',
            name='entry_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 1, 23, 53, 3, 357555, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 23, 53, 3, 347818, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('L1', 'Level 1'), ('L2', 'Level 2'), ('L3', 'Level 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('PreDoc', 'Pre Doctorate'), ('PhD', 'PhD'), ('Pr', 'Professor')], default='L1', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 23, 53, 3, 347847, tzinfo=datetime.timezone.utc)),
        ),
    ]
