# Generated by Django 4.2.5 on 2023-10-02 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0010_alter_chat_created_at_alter_forum_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='content_id',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.RenameField(
            model_name='participantsforum',
            old_name='forum_id',
            new_name='forum',
        ),
        migrations.RenameField(
            model_name='participantsforum',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subjectofinterest',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='subjectofinterest',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 2, 0, 13, 34, 349485, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 2, 0, 13, 34, 350558, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 2, 0, 13, 34, 349895, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='participantsforum',
            name='entry_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 2, 0, 13, 34, 351083, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 2, 0, 13, 34, 344747, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 2, 0, 13, 34, 344777, tzinfo=datetime.timezone.utc)),
        ),
    ]
