# Generated by Django 4.2.5 on 2023-10-02 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0012_rename_created_by_forum_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 2, 9, 50, 58, 488081, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 2, 9, 50, 58, 489350, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 2, 9, 50, 58, 488641, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='participantsforum',
            name='entry_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 2, 9, 50, 58, 489977, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 2, 9, 50, 58, 482698, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 2, 9, 50, 58, 482729, tzinfo=datetime.timezone.utc)),
        ),
    ]
