# Generated by Django 4.2.5 on 2023-10-02 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0013_alter_chat_created_at_alter_forum_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='participantsforum',
            name='forum',
        ),
        migrations.RemoveField(
            model_name='participantsforum',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 2, 22, 52, 53, 988126, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageContent',
        ),
        migrations.DeleteModel(
            name='ParticipantsForum',
        ),
    ]
