# Generated by Django 4.2.5 on 2023-10-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0014_remove_forum_chat_remove_forum_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
