# Generated by Django 4.2.5 on 2023-10-18 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses_api', '0001_initial'),
        ('departments_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiclevelcourse',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments_api.department'),
        ),
        migrations.AddField(
            model_name='academiclevelcourse',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_api.academiclevel'),
        ),
    ]
