# Generated by Django 4.2.5 on 2023-10-02 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums_api', '0003_alter_forum_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 2, 23, 22, 43, 819146, tzinfo=datetime.timezone.utc)),
        ),
    ]
