# Generated by Django 4.2.5 on 2023-10-03 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums_api', '0006_alter_forum_created_at_alter_forum_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 10, 3, 0, 8, 50, 955224, tzinfo=datetime.timezone.utc)),
        ),
    ]
