# Generated by Django 4.2.5 on 2023-10-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums_api', '0009_alter_forum_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
