# Generated by Django 4.2.5 on 2023-10-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0002_alter_chat_created_at_alter_chat_id_and_more'),
        ('forums_api', '0010_alter_forum_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='chat',
        ),
        migrations.AddField(
            model_name='forum',
            name='messages',
            field=models.ManyToManyField(related_name='forum_messages', to='messages_api.message'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
