# Generated by Django 4.2.7 on 2024-01-21 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0014_alter_postmedia_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_posts', to='posts_api.post'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommended_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
