# Generated by Django 4.2.5 on 2023-10-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
