# Generated by Django 4.2.5 on 2023-10-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0003_remove_message_chat_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
